### ISSUE TITLE
How to build the project?

### ISSUE THREAD

**Issue by randomguy4444** [MythicAgents/poseidon#11]
Hi,

It is not clear from the README on how to build the project. So I tried:

```
joe@ubuntu:~/go/src/poseidon/Payload_Type/poseidon/agent_code$ go build
# github.com/MythicAgents/poseidon/Payload_Type/poseidon/agent_code
./poseidon.go:163:13: undefined: profiles.New
```

The profiles package contains two New() method in two different files. How should I build?

**Comment by its-a-feature** [comment]
I just merged a PR into the primary branch that should help you. There's now a Makefile in the project. To build, simply `cd` into the `agent_code` folder. From there, you can run the commands in the Makefile to build some versions of the agents. You'll need to edit the variables at the top of the Makefile though
