### ISSUE TITLE
Compilation of ARM payloads

### ISSUE THREAD

**Issue by asaurusrex** [MythicAgents/poseidon#28]
This is just a suggested change to include options to allow users to compile to ARM vs. x86.  To compile ARM payloads I had to change two files:
https://github.com/MythicAgents/poseidon/blob/master/Payload_Type/poseidon/mythic/agent_functions/builder.py, change 
```
command = f"rm -rf /build; rm -rf /deps; CGO_ENABLED=1 GOOS={target_os} GOARCH=amd64 "
```
to 
```
command = f"rm -rf /build; rm -rf /deps; CGO_ENABLED=1 GOOS={target_os} GOARCH=arm64 "
```
and in https://github.com/MythicAgents/poseidon/blob/master/Payload_Type/poseidon/agent_code/poseidon.go, comment out all references to libinject from the code (this module does not work as written for ARM and will cause compile errors).
After that you should be good to go.

**Comment by its-a-feature** [comment]
Added in!
