### ISSUE TITLE
Builds fail with "go: updates to go.mod needed; to update it:" error

### ISSUE THREAD

**Issue by stephenbradshaw** [MythicAgents/poseidon#43]
Using commit c63e0f590e7e7525298bbcb4d88b6acf7194c99e of Poseidon, builds of the payload in Mythic 2.3.13 fail with output similar to the following.

```
STDERR:

[STDERR]
go: updates to go.mod needed; to update it:
	go mod tidy
/build/poseidon-linux-amd64 does not exist
```

I was able to fix the issue on my system and make builds work again by [reversing this particular part](https://github.com/MythicAgents/poseidon/commit/62b6a4e622957f50887628396c247eafa7144a2e#diff-373538c435bb502248bab64aaa88d8de307a450c6e564cf3ce246a2fd718b1d8L3) of commit  62b6a4e622957f50887628396c247eafa7144a2e to change the go version in `Payload_Type/poseidon/agent_code/go.mod` back to the previous value of `1.15`.

**Comment by its-a-feature** [comment]
I don't think we have this in the current main branch, but please reopen this if you encounter it again
