### ISSUE TITLE
Build will fail as execute_macho go source files are located in the wrong directory

### ISSUE THREAD

**Issue by 0x09AL** [MythicAgents/poseidon#46]
Tried to build the latest version of poseidon but the build was not successful. The reason behind it because this folder is placed in the wrong location:

https://github.com/MythicAgents/poseidon/tree/master/Payload_Type/poseidon/agent_code/execute_macho

```
#8 15.67        github.com/MythicAgents/poseidon/Payload_Type/poseidon/agent_code/pkg/utils/structs: module github.com/MythicAgents/poseidon/Payload_Type/poseidon@latest found (v0.0.0-20230510142239-d7316c849410), but does not contain package github.com/MythicAgents/poseidon/Payload_Type/poseidon/agent_code/pkg/utils/structs
#8 15.68 make: *** [Makefile:15: build] Error 1
```

This folder should be removed as these files are already located in the correct place:
https://github.com/MythicAgents/poseidon/tree/master/Payload_Type/poseidon/poseidon/agent_code/execute_macho

**Comment by its-a-feature** [comment]
Oh wow, yeah something happened when the v3.0.0 branch merged into the main branch. Thanks for the catch!

**Comment by its-a-feature** [comment]
ok, that should be good now

**Comment by 0x09AL** [comment]
Thank you for the quick fix
