### ISSUE TITLE
portscan command does not scan

### ISSUE THREAD

**Issue by timukas** [MythicAgents/poseidon#50]
Hi,

Using latest poseidon with latest Mythic on Linux. When running **portscan**, then error is shown:

`json: cannot unmarshal array into Go struct field PortScanParams.ports of type string`

Launching 'tcpdump' also does not show any traffic to scanned host.

p.s. other built-in commands work fine.

**Comment by its-a-feature** [comment]
Yup, can reproduce. I'll have a fix for this pushed tomorrow

**Comment by its-a-feature** [comment]
I just pushed a fix for this - v 2.0.13

**Comment by timukas** [comment]
Tested 'portscan' with latest poseidon version. 

Now defined target(s) are scanned and i get the results.
