### ISSUE TITLE
'shell' command output truncates the output

### ISSUE THREAD

**Issue by timukas** [MythicAgents/poseidon#51]
Hi,

Latest poseidon (default build) payload truncates 'shell' command output.
E.g. "shell dmesg" shows only 1034 lines in output window. Running 'dmesg | wc -l' in terminal shows 2056 lines.
Running 'shell dmesg' next time, shows 1371 lines.

Similar with 'shell ps auxf', poseidon output in Mythic shows less lines than same command in terminal.

And amount of lines shown in Mythic output is every time random, but always smaller than actual number of output in terminal.

Seems like a bug?

**Comment by its-a-feature** [comment]
I can reproduce. Thank you for catching this! Working on a fix

**Comment by its-a-feature** [comment]
Just pushed a fix for this in version 2.0.14 (it also should have affected the `run` command, but both should be fixed)

**Comment by timukas** [comment]
Checked with latest version - now output is not truncated.

Kudos for fixing it!
