### ISSUE TITLE
Developing new commands doesn't work (default behavior)

### ISSUE THREAD

**Issue by coolcoolnoworries** [MythicAgents/poseidon#54]
Looks like theres an undocumented quirk when developing and adding new commands that has them not build or show up. The .env has the POSEIDON_USE_BUILD_CONTEXT var set to false by default, so even if you follow the right steps from https://github.com/MythicAgents/poseidon/blob/055eb06e6fdc31ae4b0718dcaa2f6522c7e66b41/documentation-payload/poseidon/development.md, the commands never get built in (looks like it just pulls from main remote repo). 

You have to set POSEIDON_USE_BUILD_CONTEXT to true, and then itll pull your added code from the local InstalledServices/poseidon folder like it should. This drove me nuts for awhile. Might be worth throwing in a note about it in the docs 🙏

**Comment by its-a-feature** [comment]
Very good point! This isn't actually something that's poseidon specific, but applies to all agents that leverage pre-built containers. I just released a blog about it (https://medium.com/@its_a_feature_/agent-customization-in-mythic-tailoring-tools-for-red-team-needs-1746fd02177f) and will be incorporating it into agent docs and the global docs at https://docs.mythic-c2.net/.

**Comment by coolcoolnoworries** [comment]
Awesome, ty!
