### ISSUE TITLE
wrong variable name for poseidon_tcp_initial_config

### ISSUE THREAD

**Issue by XCVYN6UGT85JywuH** [MythicAgents/poseidon#55]
poseidon_tcp.go file

```
// All variables must be a string so they can be set with ldflags
var tcp_initial_config string
```

tcp_initial_config should be poseidon_tcp_initial_config

**Comment by its-a-feature** [comment]
Good catch! When this is finished (https://github.com/MythicAgents/poseidon/actions/runs/8647770064) you should be able to re-install poseidon via mythic-cli and properly compile poseidon_tcp
