### ISSUE TITLE
Cross-compilation error in macOS

### ISSUE THREAD

**Issue by Bash-and-tea** [MythicAgents/poseidon#57]
When trying to compile a payload against AMD_64 Linux from an ARM64 macOS MythicC2 instance, the build fails with this error:

```
Sending Build command
Compilation failed with errors
StdErr: 
# runtime/cgo
gcc: error: unrecognized command-line option '-m64'
```

Same behavior is displayed under the same conditions (trying to build a payload against AMD64 Linux from an ARM macOS host) for the freyja agent as well. Is there any way to fix the malformed architecture specifying cmdline option from within the existing Poseidon container or build spec?

Thank you!

**Comment by its-a-feature** [comment]
I can see the same error when I try to build for amd64 Linux from an ARM64 macOS instance. Interestingly, I don't get the same error when I build for amd64 macOS from arm64 macOS. I also don't see the `-m64` flag in the code anywhere, so I'm gonna have to trace this down to see where it's coming from .

**Comment by its-a-feature** [comment]
https://github.com/MythicAgents/poseidon/actions/runs/10709004720
^ when this finishes, try pulling down the latest Poseidon. I figured out where the issue was and updated the build process and toolchains to account for building amd64 on arm64

**Comment by its-a-feature** [comment]
I'm going to close this now as working, but if you continue to have the issue or run into another one, please continue to open issues!
