### ISSUE TITLE
Payload Failed to Build

### ISSUE THREAD

**Issue by timukas** [MythicAgents/poseidon#60]
Latest poseidon fails to build:

```
Sending Build command
Compilation failed with errors
StdErr: 
# runtime/cgo
cgo: C compiler "x86_64-linux-gnu-gccGOGARBLE=*" not found: exec: "x86_64-linux-gnu-gccGOGARBLE=*": executable file not found in $PATH

exit status 1
StdOut:
```

p.s looks like missing space in `Payload_Type/poseidon/poseidon/agentfunctions/builder.go` on line 448?

**Comment by its-a-feature** [comment]
I think you're exactly right. I added the missing space and started a new build (https://github.com/MythicAgents/poseidon/actions/runs/10719785598). Once that's done, you should be able to reinstall poseidon and rebuild your payload to get it to work

**Comment by timukas** [comment]
Now successfully built payload.

**Comment by its-a-feature** [comment]
Awesome! Thanks again for catching that! I was doing testing on a remote computer to fix the arm -> x64 builds and must have just missed that space when I moved it over into git.
